export const TRADES_LIST_REQUEST = 'app/trade/TRADES_LIST_REQUEST';
export const TRADES_LIST_SUCCESS = 'app/trade/TRADES_LIST_SUCCESS';
export const TRADES_LIST_FAILURE = 'app/trade/TRADES_LIST_FAILURE';

export const TRADE_OPERATION_REQUEST = 'app/trade/TRADE_OPERATION_REQUEST';
export const TRADE_OPERATION_SUCCESS = 'app/trade/TRADE_OPERATION_SUCCESS';
export const TRADE_OPERATION_FAILURE = 'app/trade/TRADE_OPERATION_FAILURE';
